name: Docker Image CI

on:
  push:
    branches: [ "master" ]

    

jobs:    
  check-links:
    runs-on: ubuntu-latest
    steps:
      - name: Pruebas de SAST
        run: echo "Ejecución de Pruebas de SAST"  
   
      - name: Crear archivo
        writeFile file: 'credentials.ini', text: '''[credentials]
                user=${CREDS_USR}
                password=${CREDS_PSW}'''
      
      - name: Build docker image
        run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
